import type { AnalysisResult } from './types'
import { formatNumber } from './utils'

export function buildReportText(fileName: string, result: AnalysisResult) {
  const summary = [
    `Source file: ${fileName}`,
    `House style profile: ${result.appliedProfileName}`,
    `Files processed: ${formatNumber(result.summary.filesProcessed)}`,
    `Paragraphs scanned: ${formatNumber(result.summary.paragraphs)}`,
    `Runs scanned: ${formatNumber(result.summary.runs)}`,
    `Text nodes scanned: ${formatNumber(result.summary.textNodes)}`,
    `Manual line breaks detected: ${formatNumber(result.summary.manualBreaks)}`,
    `Tabs detected: ${formatNumber(result.summary.tabs)}`,
    `Double spaces fixed: ${formatNumber(result.summary.doubleSpacesFixed)}`,
    `Tabs normalized: ${formatNumber(result.summary.tabsNormalized)}`,
    `Trailing whitespace fixed: ${formatNumber(result.summary.trailingWhitespaceFixed)}`,
    `Blank paragraphs collapsed: ${formatNumber(result.summary.blankParagraphsCollapsed)}`,
    `Dominant fonts: ${result.dominantFonts.join(', ') || 'Not detected'}`,
    `Dominant sizes: ${result.dominantSizes.join(', ') || 'Not detected'}`,
    `Word parts processed: ${result.processedParts.join(', ') || 'document.xml'}`,
    `Watchlist hits: ${result.watchTermsFound.join(', ') || 'None'}`,
  ]

  const issues =
    result.issues.length === 0
      ? ['No formatting issues flagged beyond auto-fixed cleanup items.']
      : result.issues.map(
          (issue) =>
            `[${issue.severity.toUpperCase()}] ${issue.title} | ${issue.location} | ${issue.detail} | occurrences: ${issue.occurrences}`,
        )

  const preview = result.preview.length === 0 ? ['No plain-text preview available.'] : result.preview

  return [
    'Document Production Automation Report',
    '===================================',
    '',
    'Summary',
    '-------',
    ...summary,
    '',
    'Flagged Issues',
    '--------------',
    ...issues,
    '',
    'Preview Extract',
    '---------------',
    ...preview,
    '',
    'Generated by Nightshift-proof document cleanup prototype.',
    '',
  ].join('\n')
}
